### ISSUE TITLE
Choose a static site generator for Observe k8s website

### ISSUE THREAD

**Issue by kenfinnigan** [observe-k8s/observe-k8s.github.io#1]

**Comment by halcyondude** [comment]
I've been experimenting with the following, which I'm planning to use for the cncf/landscape-graph as well as the tag's gitpages site.

* https://kit.svelte.dev, using https://kit.svelte.dev/docs/adapter-static
* https://www.skeleton.dev, in combination w/ sveltekit.  Let's connect, I can show you a prototype starter/seed site, would welcome the feedback.

**Comment by kenfinnigan** [comment]
@nate-double-u I saw your comment on https://github.com/cncf/tag-observability/issues/39 regarding a Hugo site for TAG Observability. As the Observe k8s Working Group is part of TAG Observability, are we able to have a site set up for us?

Thanks

**Comment by nate-double-u** [comment]
Hi @kenfinnigan, sorry for the delay on this. I think a request like that would have to go through the CNCF Service Desk.

**Comment by kenfinnigan** [comment]
Is this something you can trigger @halcyondude or @alolita? Thanks

**Comment by alolita** [comment]
@kenfinnigan I think a ServiceDesk ticket needs to be opened to set up a github.io page. Lets chat.

**Comment by nate-double-u** [comment]
Thanks for that @alolita!

**Comment by kenfinnigan** [comment]
This is done.

I took the docsy themed site from TAG Observability and tweaked it for Observe k8s and GH Action runners
